service:
  port: 8080


spring:
  datasource:
    url: jdbc:mysql://localhost:3306/toutiao?useUnicode=true&characterEncoding=utf-8&serverTimezone=Asia/Shanghai
    username: root
    password: root
    driver-class-name: com.mysql.cj.jdbc.Driver
  velocity:
    suffix: .html
    cache: false
    toolbox-config-location: toolbox.xml
mybatis:
  mapper-locations: classpath:dao/*.xml
  config-location: classpath:mybatis-config.xml
aliyun:
  oss:
    endpoint: oss-cn-beijing.aliyuncs.com # oss对外服务的访问域名
    accessKeyId: LTAI4FshVqXLYPdjM3XLEgRw # 访问身份验证中用到用户标识
    accessKeySecret: WKWU5LUps5KJEf8q86mCda6qoH1vEb # 用户用于加密签名字符串和oss用来验证签名字符串的密钥
    bucketName: song-oss # oss的存储空间
    policy:
      expire: 300 # 签名有效期(S)
    maxSize: 10 # 上传文件大小(M)
    callback: http://www.asong.cloud:8080/aliyun/oss/callback # 文件上传成功后的回调地址
    dir:
      prefix: shop/images/ # 上传文件夹路径前缀